apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: team

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: ai-interviewer
        metrics_path: /metrics
        static_configs:
          - targets:
              - "10.0.0.158:5001"
              
              