apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-serving
  labels:
    app: serving
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: serving
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
